# Generated by Django 5.2.7 on 2025-10-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile'),
    ]

    operations = [
    ]
