# Generated by Django 5.2.7 on 2025-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reserve_percentage',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
