# Generated by Django 5.2.7 on 2025-10-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_target_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reserve_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
