# Generated by Django 5.2.7 on 2025-10-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transaction_reserve_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reserve_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
